# Generated by Django 6.0.1 on 2026-02-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="优惠券名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="优惠券代码"),
                ),
                (
                    "coupon_type",
                    models.CharField(
                        choices=[
                            ("discount", "满减券"),
                            ("percentage", "折扣券"),
                            ("cash", "现金券"),
                        ],
                        max_length=20,
                        verbose_name="优惠券类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "可用"),
                            ("inactive", "不可用"),
                            ("expired", "已过期"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "discount_amount",
                    models.FloatField(
                        blank=True, null=True, verbose_name="优惠金额（满减券/现金券）"
                    ),
                ),
                (
                    "discount_rate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="折扣率（折扣券，0-1）"
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.FloatField(default=0, verbose_name="最低消费金额"),
                ),
                (
                    "max_discount_amount",
                    models.FloatField(blank=True, null=True, verbose_name="最大折扣金额"),
                ),
                (
                    "total_count",
                    models.IntegerField(blank=True, null=True, verbose_name="总发放数量"),
                ),
                ("used_count", models.IntegerField(default=0, verbose_name="已使用数量")),
                ("user_limit", models.IntegerField(default=1, verbose_name="每用户限领数量")),
                ("valid_from", models.DateTimeField(verbose_name="生效时间")),
                ("valid_until", models.DateTimeField(verbose_name="失效时间")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="使用说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="活动标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="活动描述"),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("flash_sale", "限时抢购"),
                            ("package", "套餐活动"),
                            ("discount", "折扣活动"),
                        ],
                        max_length=20,
                        verbose_name="活动类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "进行中"),
                            ("ended", "已结束"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="活动图片"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "discount_rate",
                    models.FloatField(blank=True, null=True, verbose_name="折扣率（0-1）"),
                ),
                (
                    "discount_amount",
                    models.FloatField(blank=True, null=True, verbose_name="折扣金额"),
                ),
                (
                    "min_purchase_amount",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="最低消费金额"
                    ),
                ),
                (
                    "max_discount_amount",
                    models.FloatField(blank=True, null=True, verbose_name="最大折扣金额"),
                ),
                (
                    "total_limit",
                    models.IntegerField(blank=True, null=True, verbose_name="总限购数量"),
                ),
                (
                    "user_limit",
                    models.IntegerField(
                        blank=True, default=1, null=True, verbose_name="每用户限购数量"
                    ),
                ),
                ("sold_count", models.IntegerField(default=0, verbose_name="已售数量")),
                (
                    "applicable_sheep_ids",
                    models.TextField(
                        blank=True, null=True, verbose_name="适用羊只ID列表（JSON格式）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "优惠活动",
                "verbose_name_plural": "优惠活动",
                "db_table": "promotion_activities",
                "ordering": ["-start_time"],
            },
        ),
        migrations.AddField(
            model_name="sheep",
            name="ear_tag",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="耳标编号"
            ),
        ),
        migrations.AddField(
            model_name="sheep",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="qrcodes/", verbose_name="二维码"
            ),
        ),
        migrations.AlterField(
            model_name="sheep",
            name="gender",
            field=models.IntegerField(choices=[(0, "母"), (1, "公")], verbose_name="性别"),
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("used", "已使用"),
                            ("expired", "已过期"),
                        ],
                        default="unused",
                        max_length=20,
                        verbose_name="使用状态",
                    ),
                ),
                (
                    "obtained_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="领取时间"),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "order_id",
                    models.IntegerField(blank=True, null=True, verbose_name="使用的订单ID"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="sheep_management.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="sheep_management.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "db_table": "user_coupons",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="user_coupon_user_id_eaaee2_idx"
                    ),
                    models.Index(
                        fields=["coupon", "status"],
                        name="user_coupon_coupon__f202a6_idx",
                    ),
                ],
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
