# Generated by Django 6.0.1 on 2026-02-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheep",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="价格（元）"
            ),
        ),
    ]
