# Generated by Django 6.0.1 on 2026-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0009_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sheep_videos/', verbose_name='羊只视频'),
        ),
    ]
