# Generated by Django 6.0.1 on 2026-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0010_sheep_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='breed',
            field=models.CharField(choices=[('滩羊', '滩羊'), ('小尾寒羊', '小尾寒羊'), ('杜泊羊', '杜泊羊'), ('萨福克羊', '萨福克羊'), ('特克塞尔羊', '特克塞尔羊'), ('其他', '其他')], default='滩羊', max_length=50, verbose_name='品种'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='health_status',
            field=models.CharField(choices=[('健康', '健康'), ('良好', '良好'), ('一般', '一般'), ('需关注', '需关注'), ('生病', '生病')], default='健康', max_length=20, verbose_name='健康状况'),
        ),
    ]
