# Generated by Django 6.0.1 on 2026-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0011_sheep_breed_sheep_health_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='送达日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='物流公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics_tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='物流单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发货日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付/认养中'), ('shipping', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
