# Generated by Django 6.0.1 on 2026-02-27 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheep_management', '0012_order_delivery_date_order_logistics_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号'),
        ),
        migrations.CreateModel(
            name='EnvironmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('temperature', '温度异常'), ('humidity', '湿度异常'), ('air_quality', '空气质量异常'), ('motion', '异常移动'), ('other', '其他')], max_length=20, verbose_name='预警类型')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='严重程度')),
                ('message', models.TextField(verbose_name='预警信息')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='位置')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_alerts', to=settings.AUTH_USER_MODEL, verbose_name='所属养殖户')),
            ],
            options={
                'verbose_name': '环境预警',
                'verbose_name_plural': '环境预警',
                'db_table': 'environment_alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
