# Generated by Django 6.0.1 on 2026-03-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sheep_management",
            "0020_feedingrecord_replace_startdate_enddate_with_feeddate",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="纬度"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="经度"
            ),
        ),
        migrations.AlterField(
            model_name="feedingrecord",
            name="feed_date",
            field=models.DateField(verbose_name="喂养日期"),
        ),
    ]
