# Generated by Django 6.0.1 on 2026-03-12 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sheep_management", "0027_news_top_slot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreederFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "养殖户关注关系",
                "verbose_name_plural": "养殖户关注关系",
                "db_table": "breeder_follows",
            },
        ),
        migrations.RenameIndex(
            model_name="qalog",
            new_name="qa_logs_created_9d050d_idx",
            old_name="qa_logs_created_50cd7e_idx",
        ),
        migrations.RenameIndex(
            model_name="qalog",
            new_name="qa_logs_questio_25e958_idx",
            old_name="qa_logs_questio_80ff8f_idx",
        ),
        migrations.RenameIndex(
            model_name="qalog",
            new_name="qa_logs_success_8fd4ff_idx",
            old_name="qa_logs_success_4fa7d6_idx",
        ),
        migrations.RenameIndex(
            model_name="qalog",
            new_name="qa_logs_fallbac_afefa2_idx",
            old_name="qa_logs_fallbac_0343f1_idx",
        ),
        migrations.AddField(
            model_name="breederfollow",
            name="breeder",
            field=models.ForeignKey(
                limit_choices_to={"role": 1},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breeder_followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="养殖户",
            ),
        ),
        migrations.AddField(
            model_name="breederfollow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_breeders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="breederfollow",
            index=models.Index(fields=["user"], name="breeder_fol_user_id_fec160_idx"),
        ),
        migrations.AddIndex(
            model_name="breederfollow",
            index=models.Index(
                fields=["breeder"], name="breeder_fol_breeder_9e1600_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="breederfollow",
            unique_together={("user", "breeder")},
        ),
    ]
